ktor {
    application {
        modules = [ hu.tb.meet.ApplicationKt.module ]
    }
    deployment {
        port = 8081
        port = ${?PORT}
    }
}

database {
    url = "jdbc:sqlite:./data/meeting.db"
    url = ${?DATABASE_URL}
}

jwt {
    realm = "meeting-server"
    issuer = "hu.tb.meet"
    audience = "meeting-users"
    secret = "dev-secret-change-me"
    secret = ${?JWT_SECRET}
}
