[versions]
java = "21"
kotlin = "2.3.20"
ktor = "3.4.2"
jib = "3.5.4"
exposed = "1.1.1"
sqlite = "3.50.2.0"
koin = "4.2.2"
logback = "1.5.35"
bcrypt = "0.10.2"

[libraries]
exposed-core = { group = "org.jetbrains.exposed", name = "exposed-core", version.ref = "exposed" }
exposed-jdbc = { group = "org.jetbrains.exposed", name = "exposed-jdbc", version.ref = "exposed" }
exposed-dao = { group = "org.jetbrains.exposed", name = "exposed-dao", version.ref = "exposed" }

sqlite = { group = "org.xerial", name = "sqlite-jdbc", version.ref = "sqlite" }

koin-ktor = { module = "io.insert-koin:koin-ktor", version.ref = "koin" }
koin-loggerSlf4j = { module = "io.insert-koin:koin-logger-slf4j", version.ref = "koin" }

logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

bcrypt = { module = "at.favre.lib:bcrypt", version.ref = "bcrypt" }

[bundles]
koin = ["koin-ktor", "koin-loggerSlf4j"]
exposed = ["exposed-core", "exposed-jdbc", "exposed-dao"]

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor" }
jib = { id = "com.google.cloud.tools.jib", version.ref = "jib" }
